### ISSUE TITLE
Bootstrapping Anchors - APHRODITE

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/Aphrodite#5]
Hello @jmbanda ,

While I was reading your paper, I came across the below para

`"Once an initial set of anchors is found (i.e. concepts identified in section Building an imperfectly labeled cohort), they can be bootstrapped, with some human guidance, to find more anchors in a data driven manner. In the anchor-searching setting, we train a logistic regression classifier with strong L1- regularization to predict the presence or absence of the initial anchors."`

1) I did see in your YouTube video where the user reviews the keyword list (concept list) and selects only the relevant items. But may I know what do you mean by "finding more anchors in data driven manners". In addition I also see that you use log regression to predict presence or absence of initial anchors? 

I did see in another referenced/related paper where user reviews the Anchor through a User Interface where user can see the performance of the model based on Inclusion or Exclusion of certain Anchors. But through APHRODITE, can we do the same? Instead of UI is it a notepad file?

Can I kindly request you to elaborate and help me understand this better?

**Comment by jmbanda** [comment]
The UI for the Anchors implementation is part of the original work that was not even setup to run on the OMOP CDM. I have not adopted the UI into APHRODITE, you can only selected at the end of the anchors run via the text file.
