### ISSUE TITLE
Installation Issues - APHRODITE

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/Aphrodite#8]
Hello @jmbanda ,

I was trying to install APHRODITE using my RStudio which has an R version of 3.6.2 but it doesn't work. I get the below error

```
Error: Failed to install 'Aphrodite' from GitHub:
  (converted from warning) unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.6:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.6/PACKAGES'
```

When I restart my RStudio and try the installation again, I get the below error message

```
Error: Failed to install 'Aphrodite' from GitHub:
  (converted from warning) installation of package ‘C:/Users/test/AppData/Local/Temp/RtmpSYIjVb/file38984ce36c21/Aphrodite_2.0.tar.gz’ had non-zero exit status
```
 
So, I downgraded my R version in RStudio to R 3.1.2 but the other dependencies like devtools doesn't support the R version.

Can you guide me on this please?

**Comment by jmbanda** [comment]
Can you provide more context as to how you are trying to install the package? I have tested APHRODITE on R versions 3.5.X with no problems.

**Comment by SSMK-wq** [comment]
Hi @jmbanda ,

I just did the below

```
install.packages("devtools")
install.packages("drat")
drat::addRepo("OHDSI")
library(devtools)
install.packages("FeatureExtraction")
install.packages("DatabaseConnector")
install.packages("SqlRender")
install.packages("PatientLevelPrediction")
install.packages("dplyr")
install.packages("stringr")
install.packages("data.table")
install_github("OHDSI/Aphrodite")
```

**Comment by jmbanda** [comment]
Just try:

library(devtools)
install_github("OHDSI/Aphrodite")

**Comment by SSMK-wq** [comment]
Hi,

It's the same error. I have given a more detailed log message

```
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\test\AppData\Local\Temp\RtmpcnE6nN\downloaded_packages
> library(devtools)
Loading required package: usethis
Warning messages:
1: package ‘devtools’ was built under R version 3.6.3 
2: package ‘usethis’ was built under R version 3.6.3 
> install_github("OHDSI/Aphrodite")
Downloading GitHub repo OHDSI/Aphrodite@master
√  checking for file 'C:\Users\test\AppData\Local\Temp\RtmpcnE6nN\remotes4b40621e1e82\OHDSI-Aphrodite-72c8e77/DESCRIPTION' (1s)
-  preparing 'Aphrodite': (602ms)
√  checking DESCRIPTION meta-information ... 
-  excluding invalid files (382ms)
   Subdirectory 'man' contains invalid file names:
     'Aphrodite.pdf'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'Aphrodite_2.0.tar.gz'
   
Installing package into ‘C:/Users/test/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'Aphrodite' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'data.table' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'Aphrodite'
* removing 'C:/Users/test/Documents/R/win-library/3.6/Aphrodite'
Error: Failed to install 'Aphrodite' from GitHub:
  (converted from warning) installation of package ‘C:/Users/test/AppData/Local/Temp/RtmpcnE6nN/file4b406c302825/Aphrodite_2.0.tar.gz’ had non-zero exit status
```

**Comment by jmbanda** [comment]
It seems like when you downgraded, you did not remove the 'new' versions of the packages you already installed:

`Error: (converted from warning) package 'data.table' was built under R version 3.6.3
`
My recommendation is to clean up all packages under the new R version and re-install them.

**Comment by SSMK-wq** [comment]
Hi, 

Thanks. I did clear all my R folders and temp folders and re-run the installation using the below code which resulted in error. Please note that as APHRODITE depends on R >=3.1 or 3.2, I upgraded my R version to 3.6.2

```
install.packages("devtools")
library(devtools)
install_github("OHDSI/Aphrodite")
```

```
Downloading GitHub repo OHDSI/Aphrodite@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: ffbase (0.12.7 -> 0.12.8) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
ffbase (0.12.7 -> 0.12.8) [CRAN]
Installing 1 packages: ffbase
Installing package into ‘C:/Users/ephssmk/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'Aphrodite' from GitHub:
  (converted from warning) unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.6:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.6/PACKAGES'
```

I cleared all the packages which were downloaded and temp files and re-installed them.

**Comment by jmbanda** [comment]
This seems like it might be related to this:

https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578

**Comment by SSMK-wq** [comment]
Unfortunately the suggested solution doesn't fix the above issue. Same error as is.

**Comment by jmbanda** [comment]
Unfortunately this is more of an R error and not an APHRODITE install issue.  I would delete R and all packages. Re-install and if this persists, do some Googling around. I have upgraded to the R version you mention on a test VM I have and I was able to install the package with no issues.

**Comment by SSMK-wq** [comment]
Hi,

May I check with you on how did you do it? Meaning did you install dependencies separately using multiple install_packages command and then ran install_github("OHDSI/APHRODITE") or you used dependencies = TRUE? I tried both and cleared everything.

So, would you mind if I request you for the code that you tested in the VM?

**Comment by jmbanda** [comment]
I copied and pasted your code. I am running all installations in the command line interactive R session using sudo. 

Once you run APHRODITE there will be additional packages to install depending on the Caret ML models you are running.

**Comment by SSMK-wq** [comment]
Thanks. If you have time, may I also kindly request your assistance with other queries in github? 

In the meantime, I will somehow try to get this issue fixed.

**Comment by bbolker** [comment]
@jmbanda, is the drat repository structure on the GH pages up to date, i.e. does it have a 3.6 directory for binaries? This looks like it could be part of the problem (and could be  a reason that it works in R 3.5.x but not 3.6.x)

**Comment by SSMK-wq** [comment]
The installation issue (R issue) was resolved after I used the below command

`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

Hence closing the issue
